# Generated by Django 3.0.7 on 2020-06-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id_departments', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(help_text='Enter field documentation', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitles',
            fields=[
                ('id_job_title', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
