# Generated by Django 3.0.6 on 2020-06-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitles',
            fields=[
                ('job_title', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
    ]
