# Generated by Django 3.0.7 on 2020-07-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Supp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supp2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp2', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
        migrations.AddField(
            model_name='jobtitles',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Supp1'),
        ),
        migrations.AddField(
            model_name='jobtitles',
            name='job1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Supp2'),
        ),
    ]
