# Generated by Django 3.0.7 on 2020-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_jobtitles_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('personnel_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email_adress', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='JobTitles',
        ),
    ]
