# Generated by Django 3.0.6 on 2020-06-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_jobtitles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
    ]
