# Generated by Django 3.0.7 on 2020-07-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20200705_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='type_of_clothing',
        ),
        migrations.DeleteModel(
            name='TypeOfClothing',
        ),
    ]
