# Generated by Django 3.0.7 on 2020-07-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20200701_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogMessage',
        ),
    ]
