# Generated by Django 3.0.6 on 2020-06-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
    ]
