# Generated by Django 3.0.7 on 2020-07-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20200705_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
